package dev.devdoctor.core.model;

public enum EvidenceType {
    COMMAND, HTTP, STACK_TRACE, LOG, SOURCE, CONFIGURATION, ENVIRONMENT, PROJECT, DEPENDENCY,
    GIT, PROCESS, PORT, DNS, TCP, DATABASE, REDIS, DOCKER, JVM, FILE, CORRELATION
}
