package dev.devdoctor.core.model;

public enum FailureClassification {
    BUILD, COMPILATION, STARTUP, CONFIGURATION, DEPENDENCY, DATABASE, NETWORK, HTTP,
    AUTHENTICATION, SPRING_CONTEXT, MIGRATION, REDIS, KAFKA, DOCKER, JVM, TEST, RUNTIME, UNKNOWN
}
